#!/bin/bash

usage () {
	echo "Usage: git f1 <refspec>"
	echo ""
	echo "Output one commit formatted as a patch."
	echo ""
}

if [ "$1" = "-h" ]; then
	usage
	exit
fi

refspec=$1
shift

if [ -n "$1" ]; then
	echo "fatal: too many arguments" > /dev/stderr
	usage > /dev/stderr
	exit 1
fi

if ! ref=$(git rev-parse --verify "${refspec:-HEAD}^{commit}"); then
	exit 1
fi

if git cat-file -p $ref | awk '
	/^parent/ {
		n++
		if (n > 1) {
			exit 1
		}
	}
	/^author/ {
		exit
	}'; then
	# not a merge
	git format-patch --stdout --notes --max-count=1 $ref
else
	echo "Warning: $ref is a merge commit" > /dev/stderr
	git show $ref
fi
